In [1]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import math
from sklearn.metrics import r2_score

% matplotlib inline

# Initial Cleaning up data

In [2]:
df = pd.read_csv('manual_reg_data.csv')
df.head()

x1  x2  x3    y
0   3   1  20  225
1   5   1  22  275
2   4   1  17  211
3   6   1  19  262
4   5   2  21  245

In [3]:
df.isnull().any()

x1    False
x2    False
x3    False
y     False
dtype: bool

In [4]:
df.duplicated().any()

False

In [6]:
X = df.iloc[:,0:3].copy()
Y = df.iloc[:, 3:]

In [7]:
X['intercept'] = 1
X = X[['intercept', 'x1', 'x2', 'x3']]
X.head()

intercept  x1  x2  x3
0          1   3   1  20
1          1   5   1  22
2          1   4   1  17
3          1   6   1  19
4          1   5   2  21

In [8]:
Y.head()

y
0  225
1  275
2  211
3  262
4  245

# Initialize weights

In [44]:
random.random()

0.9452240107924672

In [45]:
def define_w(X):
    w = []
    cols = len(X.columns)
    for i in range(cols):
        theta = 0.02*random.random() - 0.01
        w.append(theta)
        
    w = np.asarray([w])
        
    return w

In [46]:
W = define_w(X)
W

array([[-0.00198672,  0.00102038, -0.00383271,  0.00331316]])

In [47]:
W.shape

(1, 4)

In [48]:
a = [1,5,7,2,6,3]
a

[1, 5, 7, 2, 6, 3]

In [49]:
a = np.asarray(a)
a

array([1, 5, 7, 2, 6, 3])

In [50]:
a.shape

(6,)

In [51]:
a.T

array([1, 5, 7, 2, 6, 3])

In [52]:
a.T.shape

(6,)

In [53]:
a = [1,5,7,2,6,3]
a = np.asarray([a])
a

array([[1, 5, 7, 2, 6, 3]])

In [54]:
a.shape

(1, 6)

In [55]:
a.T

array([[1],
       [5],
       [7],
       [2],
       [6],
       [3]])

# Predict

In [56]:
row_1 = X.iloc[:1, :]
row_1

intercept  x1  x2  x3
0          1   3   1  20

In [57]:
np.dot(W, row_1.T)

array([[0.06350493]])

In [62]:
pred_1 = (W[0][0]*1) + (W[0][1]*3) + (W[0][2]*1) + (W[0][3]*20)
pred_1

0.06350493327713722

In [63]:
row_2 = X.iloc[1:2, :]
row_2

intercept  x1  x2  x3
1          1   5   1  22

In [64]:
np.dot(W, row_2.T)

array([[0.07217201]])

In [65]:
pred_2 = (W[0][0]*1) + (W[0][1]*5) + (W[0][2]*1) + (W[0][3]*22)
pred_2

0.07217201087621652

In [66]:
row_1_2 = X.iloc[0:2,:]
row_1_2

intercept  x1  x2  x3
0          1   3   1  20
1          1   5   1  22

In [68]:
row_1_2.T

0   1
intercept   1   1
x1          3   5
x2          1   1
x3         20  22

In [67]:
np.dot(W, row_1_2.T)

array([[0.06350493, 0.07217201]])

In [69]:
def predictions(W, X):
    preds = np.dot(W, X.T)
    
    return preds

In [70]:
preds = predictions(W, X)
preds

array([[0.06350493, 0.07217201, 0.05458583, 0.0632529 , 0.06502614,
        0.06400577, 0.0645066 , 0.06452531, 0.05789899, 0.06502614,
        0.05839982, 0.06783847, 0.06096012, 0.04973274, 0.05993974,
        0.0683393 , 0.07777796, 0.06171298, 0.0683393 , 0.06019177]])

# Compute Mean Squared Error (MSE) cost

In [71]:
preds.shape

(1, 20)

In [72]:
preds.T.shape

(20, 1)

In [73]:
(225 - preds[0][0]) **2

50596.426812901846

In [75]:
Y.shape

(20, 1)

In [76]:
test_cost = np.power(preds.T - Y, 2)
test_cost

y
0   50596.426813
1   75585.310603
2   44497.967761
3   68610.859480
4   59993.141418
5   52870.561444
6   55665.557047
7   57569.032015
8   48374.527798
9   59504.271471
10  51049.606692
11  62466.085366
12  70723.572933
13  30958.496548
14  62970.913843
15  65501.014946
16  78917.294838
17  55666.875281
18  64990.151625
19  46630.000778

In [77]:
test_cost.shape

(20, 1)

In [87]:
np.sum(np.power(preds.T - Y, 2), axis = 0)[0]

1163141.6686984617

In [90]:
np.sum(np.power(preds.T - Y, 2), axis = 0)[0]/Y.shape[0]

58157.083434923086

In [81]:
Y.shape[0]

20

In [91]:
def linear_reg_cost(preds, Y):
    squared_error = np.sum(np.power(preds.T - Y, 2), axis = 0)[0]
    MSE = squared_error/Y.shape[0]
    
    return MSE

In [92]:
cost = linear_reg_cost(preds, Y)
cost

58157.083434923086

# Gradient Descent

In [93]:
X1 = X.iloc[:, 1:2].copy()
X1.head()

x1
0   3
1   5
2   4
3   6
4   5

In [94]:
W1 = define_w(X1)
W1

array([[0.00935042]])

In [95]:
preds1 = predictions(W1, X1)
preds1

array([[0.02805127, 0.04675212, 0.03740169, 0.05610254, 0.04675212,
        0.03740169, 0.04675212, 0.03740169, 0.03740169, 0.04675212,
        0.04675212, 0.03740169, 0.06545297, 0.02805127, 0.05610254,
        0.04675212, 0.03740169, 0.04675212, 0.04675212, 0.02805127]])

In [96]:
cost1 = linear_reg_cost(preds1, Y)
cost1

58166.82195259158

In [97]:
w_test = list(range(-300,300))

In [98]:
df_gd = pd.DataFrame(columns=['W', 'cost'])
df_gd.head()

Empty DataFrame
Columns: [W, cost]
Index: []

In [ ]:
for j in range(len(w_test)):
    df_temp = None
    w_arr = np.asarray([[w_test[j]]])

    preds_j = predictions(w_arr, X1)
    cost_j = linear_reg_cost(preds_j, Y)
    
    df_temp = pd.DataFrame({"W": [np.squeeze(w_test[j])], "cost": [cost_j[0]]})
    df_gd = df_gd.append(df_temp, ignore_index = True)

In [ ]:
df_gd.head()

In [ ]:
plt.scatter(x=df_gd['W'], y=df_gd['cost'])
plt.xlabel('W1')
plt.ylabel('Cost')
plt.title('Cost vs Weight')

# Optimizing

In [ ]:
def get_gradients(X, preds, Y):
    M = Y.shape[0]
    grads = np.dot(X.T, preds.T-Y) * 2 * (1/M)
    
    return grads

In [ ]:
X.T

In [ ]:
preds.T - Y

In [ ]:
get_gradients(X, preds, Y).T * 0.02

In [ ]:
W

In [ ]:
W[0] - (get_gradients(X, preds, Y).T * 0.02)[0]

# Batch Gradient Step

In [ ]:
def gradient_descent_step(W, X, Y, learning_rate = 0.02):
    preds = predictions(W, X)
    cost = linear_reg_cost(preds, Y)[0]
    grads = get_gradients(X, preds, Y)
    
    W = W - learning_rate*grads.T
    
    return W, cost

In [ ]:
W = define_w(X)
W

In [ ]:
vals = gradient_descent_step(W, X, Y, learning_rate = 0.02)
vals

In [ ]:
W - vals

# Batch Gradient Descent

In [ ]:
X1 = X.iloc[:, :2]

In [ ]:
epochs = 200
W1 = define_w(X1)
for i in range(epochs):
    W1, cost1 = gradient_descent_step(W1, X1, Y, learning_rate = 0.04)
    print(W1, cost1)
print(W1)

In [ ]:
prev_cost = math.inf
cost1 = 0
W1 = define_w(X1)
while (prev_cost - cost1 > 0.01):
    W1, cost1 = gradient_descent_step(W1, X1, Y, learning_rate = 0.04)
    print(W1, cost1)

# Final

In [ ]:
prev_cost = math.inf
cost = 0
W = define_w(X)
while (prev_cost - cost > 0.01):
    W, cost = gradient_descent_step(W, X, Y, learning_rate = 0.001)
    print(W, cost)

In [ ]:
final_pred = predictions(W, X)
final_pred

In [ ]:
Y

In [ ]:
r2_score(Y.values, final_pred.T)

# Optional Task: Make a dynamically plotting graph to monitor Error vs number of iterations